# Tensorflow Essentials

Architecture defails of TF

www.tensorflow.org/ extend/architecture

###### Inner product of two vectors (the dot product)

In [7]:
vec1 = [1,2,3,4,5]
vec2 = [[3],[3],[2],[2],[5]]
inner_p = 0
for v1, v2 in zip(vec1, vec2):
    print(v1,v2)
    inner_p += v1 * v2[0]

inner_p

1 [3]
2 [3]
3 [2]
4 [2]
5 [5]


48

In [8]:
# Inner/Dot product via Numpy

import numpy as np

inner_p = np.dot(vec1, vec2)
inner_p

array([48])

In [10]:
import tensorflow as tf
import numpy as np   # Using Numpy matrices in TF

###### Tensor
* A 2x3x2 tensor is [[[1,2], [3,4], [5,6]], [[7,8], [9,10], [11,12]]]
* composed by two 3x2 matrices

* This tensor has a rank of 3.
* Tensorflow 中所有的操作子(operators)皆設計用於 Tensor 上。
* 每個 tensor object 有自己的標籤(name), 維度(shape)

In [12]:
# 表示 tensor 的不同方式：

m1 = [[1., 2.], [3., 4.]]
m2 = np.array([[1., 2.], [3., 4.]], dtype = np.float32)
m3 = tf.constant([[1., 2.], [3., 4.]])

print(type(m1))
print(type(m2))
print(type(m3))

t1 = tf.convert_to_tensor(m1, dtype=tf.float32)
t2 = tf.convert_to_tensor(m2, dtype=tf.float32)
t3 = tf.convert_to_tensor(m3, dtype=tf.float32)

print(type(t1))
print(type(t2))
print(type(t3))

<class 'list'>
<class 'numpy.ndarray'>
<class 'tensorflow.python.framework.ops.Tensor'>
<class 'tensorflow.python.framework.ops.Tensor'>
<class 'tensorflow.python.framework.ops.Tensor'>
<class 'tensorflow.python.framework.ops.Tensor'>


In [14]:
# 常用 constructions, 如：
# tf.zeros(shape)
# tf.ones(shape)

print(tf.ones([500, 500]) * 0.5)

Tensor("mul_1:0", shape=(500, 500), dtype=float32)


In [15]:
# operators
x = tf.constant([[1,2]])
negMatrix = tf.negative(x)
print(negMatrix)

Tensor("Neg:0", shape=(1, 2), dtype=int32)


* We are printing out the definition of the op, not the actual evaluation of the op.

### Useful TF operators

https://www.tensorflow.org/api_guides/python/math_ops
    
tf.add(x,y)

tf.subtract(x,y)

tf.multiply(x,y)

tf.pow(x,y)

tf.exp(x)

tf.sqrt(x)

tf.div(x,y)

tf.truediv(x,y) - same as tf.div, except casts the arguments as a float

tf.floordiv(x,y) - same as treudiv, except rounds down the final answer into an integer

tf.mod(x,y) - element-wise remainder from division

In [23]:
# TODO：產生高斯分佈



### 使用 Session(s) 執行 operators

* 每個 Tensor 物件有自己的 eval() function 可以使用

In [25]:
x = tf.constant([[1., 2.]])
negMatrix = tf.negative(x)

# [I]
with tf.Session() as sess:
    print(sess.run(negMatrix))

# [II]
sess = tf.InteractiveSession()
print(negMatrix.eval())
sess.close()

[[-1. -2.]]
[[-1. -2.]]


### Graph (略，請參考官網)
### Setting session configurations

In [29]:
with tf.Session(config=tf.ConfigProto(log_device_placement=True)) as sess:
    rst = sess.run(negMatrix)

print(rst)

[[-1. -2.]]


### 三種類型的數值
Placeholder - 須等 session 執行時，才會被初始化指定值

Variable - 可變變數，必須等 session 初始化它後，才能使用。要更新變數，需使用 tf.assign()

Constant - 不可變

In [30]:
sess = tf.InteractiveSession()

In [31]:
rdata = [1., 2., 8., -1., 0., 5.5, 6., 13]
spike = tf.Variable(False)
spike.initializer.run()

for i in range(1, len(rdata)):
    if rdata[i] - rdata[i-1] > 5:
        updater = tf.assign(spike, True)
        updater.eval()
    else:
        tf.assign(spike, False).eval()
    print("Spike", spike.eval())

Spike False
Spike True
Spike False
Spike False
Spike True
Spike False
Spike True


In [32]:
sess.close()

### Save/Load variable

In [33]:
sess = tf.InteractiveSession()

rdata = [1., 2., 8., -1., 0., 5.5, 6., 13]
spike = tf.Variable(False)
spike.initializer.run()

In [34]:
# saver = tf.train.Saver()

# Load it back
# saver.restore(sess, "./spikes.ckpt")
# print(spiles.eval())

In [35]:
for i in range(1, len(rdata)):
    if rdata[i] - rdata[i-1] > 5:
        updater = tf.assign(spike, True)
        updater.eval()
    else:
        tf.assign(spike, False).eval()
    print("Spike", spike.eval())

Spike False
Spike True
Spike False
Spike False
Spike True
Spike False
Spike True


In [45]:
# FIXIT: cannot save the .ckpt

# save_path = saver.save(sess, 'spikes.ckpt')
# print("Data saved in the file: %s" % save_path)

sess.close()

### TensorBoard (略，請參考官網)