In [1]:
# Cross-Valiadation

In [8]:
import numpy as np

In [16]:
features = np.random.randn(100,5)
target = np.random.randn(100) > 0.5

print(features.shape, features[:5])
print(target.shape, target[:5])

(100, 5) [[-1.30310816 -0.16125482 -0.20508272 -0.69305063  0.31348635]
 [-0.44201947 -1.12923716 -1.75506202 -0.62736065 -0.60486283]
 [ 0.9801822   0.9657402  -0.82068504 -0.86992908 -0.31441013]
 [ 1.93122178 -0.21494114  0.02592227  0.1748929  -1.09970543]
 [-0.412823   -0.47754217 -1.25409855 -0.01775637  2.15769272]]
(100,) [False False False False False]


In [37]:
N = features.shape[0]
N_train = int(np.floor(0.7 * N))

print(N)
print(N_train)

100
70


In [28]:
idx = np.random.permutation(N) # Randomizes index
print(idx.shape)
print(idx)

(100,)
[62 18  7 15 64 70 86 24 56 51 87  6 76 14 75 84 47 48 99 49 73 92 31  1
 45 52 98 61 10 68 25 55 67 80 12 23 95 79 13 60 27 42 22 65 46 35 74  2
 30  3  8  0 58 40 32 43 21 59  4 78 44 57 16 94 11 38  9 82 85 53 29 28
 36 88 77 34 19 91 50 96 69 20 26 63 54 39 71 41 90 37 93 33 17  5 97 81
 83 72 66 89]


In [38]:
idx_train = idx[:N_train]
idx_test = idx[N_train:]
print(idx_train)
print(idx_test)

[62 18  7 15 64 70 86 24 56 51 87  6 76 14 75 84 47 48 99 49 73 92 31  1
 45 52 98 61 10 68 25 55 67 80 12 23 95 79 13 60 27 42 22 65 46 35 74  2
 30  3  8  0 58 40 32 43 21 59  4 78 44 57 16 94 11 38  9 82 85 53]
[29 28 36 88 77 34 19 91 50 96 69 20 26 63 54 39 71 41 90 37 93 33 17  5
 97 81 83 72 66 89]


In [39]:
# Split data into training and testing sets
features_train = features[idx_train,:]
target_train = target[idx_train]
features_test = features[idx_test,:]
target_test = target[idx_test]

print(features_train.shape)
print(target_train.shape)
print(features_test.shape)
print(target_test.shape)

(70, 5)
(70,)
(30, 5)
(30,)


In [40]:
# Build, predict, evaluate (to be filled out)
# model = train(features_train, target_train)
# preds_test = predict(model, features_test)
# accuracy = evaluate_acc(preds_test, target_test)

In [42]:
###
### K-Fold Cross-validation
###

In [43]:
N = features.shape[0]
K = 10

print(N)

100


In [44]:
preds_kfold = np.empty(N)
folds = np.random.randint(0, K, size=N)

print(preds_kfold.shape)
print(folds.shape)

(100,)
(100,)


In [51]:
for idx in np.arange(K):
    # Split data
    features_train = features[folds != idx,:]
    target_train = target[folds != idx]
    features_test = features[folds == idx,:]
    # print("%d:", idx, "features_train:", features_train)
    
    # Build and predict for CV fold (to be filled out)
    # model = train(features_train, target_train)
    # preds_kfold[folds == idx] = predict(model, features_test)

%d:{} 0 features_train: [[-1.30310816 -0.16125482 -0.20508272 -0.69305063  0.31348635]
 [-0.44201947 -1.12923716 -1.75506202 -0.62736065 -0.60486283]
 [ 0.9801822   0.9657402  -0.82068504 -0.86992908 -0.31441013]
 [ 1.93122178 -0.21494114  0.02592227  0.1748929  -1.09970543]
 [-0.412823   -0.47754217 -1.25409855 -0.01775637  2.15769272]
 [-0.13756337 -0.25728525  0.26836759  1.93301044  0.70418604]
 [-0.37138662 -1.03994059  0.08613047 -0.92291474  0.51287328]
 [-1.74343083  1.03538049 -0.54718785 -0.25394409 -1.81661881]
 [-0.7982211   0.02415535 -1.82522304 -1.49110483  0.52467232]
 [ 0.15811844  1.00354181 -0.3056848   0.4481329  -0.66611618]
 [-1.28885478  0.58494437  1.07032745  1.09572055 -1.38052248]
 [-0.1831043  -0.86029879  0.1749567   1.69759669  1.1240862 ]
 [ 0.3554811  -0.78244975  1.03532381  0.53460703  0.72753089]
 [-0.76741552 -0.24014765  0.14508713 -1.70600291  0.86486573]
 [-0.55230727  0.94513628 -0.91250259  0.8917068  -0.49893158]
 [-0.54991353  0.37057054  0.62

In [52]:
# accuracy = evaluate_acc(preds_kfold, target)

使用 Cross-Validation(CV) 要注意一些事項：

1. CV 假設了一個前提：訓練集資料分布「代表」了測試集資料分佈。如果否，CV 得到的誤差與預測結果可能會太樂觀了。因此，要確保盡量減小訓練集與測試集之間，資料分布的差異性。
2. 某些資料可能使用了暫時性的特徵：譬如，要使用上個月收入來預測這個月收入，那麼我們要確保在建立訓練集資料或是每次做 k-Fold 時，訓練集的資料都不可以比測試集的資料新。
3. k 值越大，得到誤差越小、但是需要運算的時間變長。因此，條件許可下，建議至少使用 k = 10. 或是使用  leave-one-out cross-validation (k = number of data instances)